export enum PaymentProvider {
  MOBILE_MONEY = 'MOBILE_MONEY',
  BANK_TRANSFER = 'BANK_TRANSFER',
  MICRO_LENDING = 'MICRO_LENDING',
}

export enum TransactionState {
  INITIATED = 'INITIATED',
  IN_PROGRESS = 'IN_PROGRESS',
  ESCROW_HELD = 'ESCROW_HELD',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
