import React, { useState } from 'react';
import {
  BarChart3,
  PieChart as PieChartIcon,
  TrendingUp,
  Calendar,
  Filter,
  Download,
  Save,
  Plus,
  X,
  Move,
  Eye,
  Settings,
  FileText,
  Mail,
  Clock,
  Sparkles,
  GripVertical
} from 'lucide-react';
import { StandardDataTable, type Column } from '../../../components/EnliteUI/Tables';
import {
  BarChart,
  Bar,
  LineChart,
  Line,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer
} from 'recharts';

interface ReportWidget {
  id: string;
  type: 'metric' | 'chart' | 'table' | 'text';
  title: string;
  dataSource: string;
  chartType?: 'bar' | 'line' | 'pie' | 'area';
  position: { x: number; y: number };
  size: { width: number; height: number };
  filters?: any[];
  config?: any;
}

interface ReportTemplate {
  id: string;
  name: string;
  description: string;
  widgets: ReportWidget[];
  schedule?: {
    frequency: 'daily' | 'weekly' | 'monthly';
    time: string;
    recipients: string[];
  };
}

export const CustomReportBuilder: React.FC = () => {
  const [reportName, setReportName] = useState('My Custom Report');
  const [widgets, setWidgets] = useState<ReportWidget[]>([]);
  const [selectedWidget, setSelectedWidget] = useState<ReportWidget | null>(null);
  const [isPreview, setIsPreview] = useState(false);
  const [showScheduleModal, setShowScheduleModal] = useState(false);

  // Available data sources
  const dataSources = [
    { id: 'shipments', name: 'Shipments', icon: '📦' },
    { id: 'revenue', name: 'Revenue', icon: '💰' },
    { id: 'carriers', name: 'Carriers', icon: '🚛' },
    { id: 'routes', name: 'Routes', icon: '🗺️' },
    { id: 'costs', name: 'Costs', icon: '💵' },
    { id: 'performance', name: 'Performance', icon: '📈' }
  ];

  // Widget templates
  const widgetTemplates = [
    { type: 'metric', icon: '📊', label: 'Key Metric', color: 'violet' },
    { type: 'chart', icon: '📈', label: 'Chart', color: 'blue' },
    { type: 'table', icon: '📋', label: 'Data Table', color: 'emerald' },
    { type: 'text', icon: '📝', label: 'Text Block', color: 'amber' }
  ];

  // Sample data for preview
  const sampleData = {
    shipments: [
      { month: 'Jan', value: 45 },
      { month: 'Feb', value: 52 },
      { month: 'Mar', value: 61 },
      { month: 'Apr', value: 58 },
      { month: 'May', value: 70 },
      { month: 'Jun', value: 75 }
    ],
    revenue: [
      { name: 'Transportation', value: 45000 },
      { name: 'Insurance', value: 8000 },
      { name: 'Additional', value: 3000 }
    ]
  };

  const COLORS = ['#8B5CF6', '#EC4899', '#F59E0B', '#10B981', '#3B82F6'];

  const handleAddWidget = (type: string) => {
    const newWidget: ReportWidget = {
      id: `widget-${Date.now()}`,
      type: type as any,
      title: `New ${type.charAt(0).toUpperCase() + type.slice(1)}`,
      dataSource: dataSources[0].id,
      position: { x: widgets.length * 50, y: widgets.length * 50 },
      size: { width: 400, height: 300 }
    };
    setWidgets([...widgets, newWidget]);
    setSelectedWidget(newWidget);
  };

  const handleUpdateWidget = (id: string, updates: Partial<ReportWidget>) => {
    setWidgets(widgets.map(w => w.id === id ? { ...w, ...updates } : w));
    if (selectedWidget?.id === id) {
      setSelectedWidget({ ...selectedWidget, ...updates });
    }
  };

  const handleDeleteWidget = (id: string) => {
    setWidgets(widgets.filter(w => w.id !== id));
    if (selectedWidget?.id === id) {
      setSelectedWidget(null);
    }
  };

  const handleSaveReport = () => {
    const report: ReportTemplate = {
      id: `report-${Date.now()}`,
      name: reportName,
      description: 'Custom report generated by user',
      widgets
    };
    console.log('Saving report:', report);
    // TODO: Save to backend
    alert('Report saved successfully!');
  };

  const handleExport = (format: 'pdf' | 'excel' | 'csv') => {
    console.log(`Exporting report as ${format}`);
    // TODO: Implement export logic
    alert(`Exporting as ${format.toUpperCase()}...`);
  };

  const renderWidget = (widget: ReportWidget) => {
    switch (widget.type) {
      case 'metric':
        return (
          <div className="h-full flex flex-col items-center justify-center bg-gradient-to-br from-violet-500 to-purple-600 text-white rounded-xl p-6">
            <p className="text-sm opacity-80 mb-2">{widget.title}</p>
            <p className="text-5xl font-bold">156</p>
            <p className="text-sm opacity-80 mt-2 flex items-center gap-1">
              <TrendingUp className="w-4 h-4" />
              +23.5% vs last month
            </p>
          </div>
        );

      case 'chart':
        if (widget.chartType === 'pie') {
          return (
            <div className="h-full bg-white rounded-xl p-4">
              <h4 className="font-bold text-gray-900 mb-2">{widget.title}</h4>
              <ResponsiveContainer width="100%" height="85%">
                <PieChart>
                  <Pie
                    data={sampleData.revenue}
                    cx="50%"
                    cy="50%"
                    labelLine={false}
                    outerRadius={80}
                    fill="#8884d8"
                    dataKey="value"
                  >
                    {sampleData.revenue.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip />
                  <Legend />
                </PieChart>
              </ResponsiveContainer>
            </div>
          );
        }
        return (
          <div className="h-full bg-white rounded-xl p-4">
            <h4 className="font-bold text-gray-900 mb-2">{widget.title}</h4>
            <ResponsiveContainer width="100%" height="85%">
              <BarChart data={sampleData.shipments}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="month" />
                <YAxis />
                <Tooltip />
                <Bar dataKey="value" fill="#8B5CF6" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        );

      case 'table':
        return (
          <div className="h-full bg-white rounded-xl p-4 overflow-auto">
            <h4 className="font-bold text-gray-900 mb-3">{widget.title}</h4>
            <StandardDataTable
              embedded
              dense
              searchable={false}
              pagination={false}
              columnVisibility={false}
              data={sampleData.shipments.map((row, idx) => ({
                id: String(idx),
                month: row.month,
                value: row.value,
                growth: `+${idx * 2}%`,
              }))}
              getRowId={(row) => row.id}
              columns={[
                { key: 'month', label: 'Month' },
                { key: 'value', label: 'Shipments', align: 'right' },
                {
                  key: 'growth',
                  label: 'Growth',
                  align: 'right',
                  render: (g: string) => <span className="text-emerald-600">{g}</span>,
                },
              ] as Column[]}
              emptyMessage="No sample data"
            />
          </div>
        );

      case 'text':
        return (
          <div className="h-full bg-gradient-to-br from-gray-50 to-white rounded-xl p-6 border-2 border-gray-200">
            <h4 className="font-bold text-gray-900 mb-2">{widget.title}</h4>
            <p className="text-gray-600 text-sm leading-relaxed">
              This is a customizable text block. You can add notes, insights, or any other information here.
            </p>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-violet-50 p-6">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">Custom Report Builder</h1>
            <p className="text-gray-600">Drag, drop, and customize your perfect report</p>
          </div>
          <div className="flex gap-3">
            <button
              onClick={() => setIsPreview(!isPreview)}
              className="px-4 py-2 border-2 border-gray-200 text-gray-700 rounded-xl hover:bg-gray-50 font-semibold transition-all flex items-center gap-2"
            >
              <Eye className="w-5 h-5" />
              {isPreview ? 'Edit' : 'Preview'}
            </button>
            <button
              onClick={() => setShowScheduleModal(true)}
              className="px-4 py-2 border-2 border-violet-600 text-violet-600 rounded-xl hover:bg-violet-50 font-semibold transition-all flex items-center gap-2"
            >
              <Clock className="w-5 h-5" />
              Schedule
            </button>
            <button
              onClick={handleSaveReport}
              className="px-4 py-2 bg-gradient-to-r from-violet-600 to-purple-600 text-white rounded-xl hover:from-violet-700 hover:to-purple-700 font-semibold transition-all flex items-center gap-2 shadow-lg"
            >
              <Save className="w-5 h-5" />
              Save Report
            </button>
          </div>
        </div>

        {/* Report Name */}
        <div className="mt-4">
          <input
            type="text"
            value={reportName}
            onChange={(e) => setReportName(e.target.value)}
            className="text-xl font-semibold border-b-2 border-transparent hover:border-violet-600 focus:border-violet-600 focus:outline-none px-2 py-1 transition-colors"
            placeholder="Report Name"
          />
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* Widget Library */}
        {!isPreview && (
          <div className="space-y-6">
            <div className="bg-white rounded-2xl p-6 border-2 border-gray-200 shadow-sm">
              <h3 className="font-bold text-gray-900 mb-4 flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-violet-600" />
                Widget Library
              </h3>
              <div className="space-y-2">
                {widgetTemplates.map((template) => (
                  <button
                    key={template.type}
                    onClick={() => handleAddWidget(template.type)}
                    className={`w-full p-4 bg-gradient-to-r from-${template.color}-50 to-${template.color}-100 hover:from-${template.color}-100 hover:to-${template.color}-200 rounded-xl transition-all text-left flex items-center gap-3 group`}
                  >
                    <div className={`text-2xl`}>{template.icon}</div>
                    <div>
                      <p className="font-semibold text-gray-900">{template.label}</p>
                      <p className="text-xs text-gray-600">Click to add</p>
                    </div>
                    <Plus className="w-5 h-5 text-gray-400 ml-auto group-hover:text-gray-600" />
                  </button>
                ))}
              </div>
            </div>

            {/* Widget Properties */}
            {selectedWidget && (
              <div className="bg-white rounded-2xl p-6 border-2 border-gray-200 shadow-sm">
                <h3 className="font-bold text-gray-900 mb-4 flex items-center gap-2">
                  <Settings className="w-5 h-5 text-violet-600" />
                  Widget Properties
                </h3>

                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Title</label>
                    <input
                      type="text"
                      value={selectedWidget.title}
                      onChange={(e) => handleUpdateWidget(selectedWidget.id, { title: e.target.value })}
                      className="w-full px-3 py-2 border-2 border-gray-200 rounded-lg focus:ring-2 focus:ring-violet-500 focus:border-violet-500"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Data Source</label>
                    <select
                      value={selectedWidget.dataSource}
                      onChange={(e) => handleUpdateWidget(selectedWidget.id, { dataSource: e.target.value })}
                      className="w-full px-3 py-2 border-2 border-gray-200 rounded-lg focus:ring-2 focus:ring-violet-500 focus:border-violet-500"
                    >
                      {dataSources.map((ds) => (
                        <option key={ds.id} value={ds.id}>
                          {ds.icon} {ds.name}
                        </option>
                      ))}
                    </select>
                  </div>

                  {selectedWidget.type === 'chart' && (
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">Chart Type</label>
                      <div className="grid grid-cols-2 gap-2">
                        {['bar', 'line', 'pie', 'area'].map((type) => (
                          <button
                            key={type}
                            onClick={() => handleUpdateWidget(selectedWidget.id, { chartType: type as any })}
                            className={`px-3 py-2 rounded-lg font-medium transition-all capitalize ${
                              selectedWidget.chartType === type
                                ? 'bg-violet-600 text-white'
                                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                            }`}
                          >
                            {type}
                          </button>
                        ))}
                      </div>
                    </div>
                  )}

                  <button
                    onClick={() => handleDeleteWidget(selectedWidget.id)}
                    className="w-full px-4 py-2 bg-rose-100 text-rose-600 rounded-lg hover:bg-rose-200 font-semibold transition-all flex items-center justify-center gap-2"
                  >
                    <X className="w-4 h-4" />
                    Delete Widget
                  </button>
                </div>
              </div>
            )}

            {/* Export Options */}
            <div className="bg-white rounded-2xl p-6 border-2 border-gray-200 shadow-sm">
              <h3 className="font-bold text-gray-900 mb-4 flex items-center gap-2">
                <Download className="w-5 h-5 text-violet-600" />
                Export Options
              </h3>
              <div className="space-y-2">
                {[
                  { format: 'pdf', icon: '📄', label: 'PDF Document' },
                  { format: 'excel', icon: '📊', label: 'Excel Spreadsheet' },
                  { format: 'csv', icon: '📋', label: 'CSV File' }
                ].map((option) => (
                  <button
                    key={option.format}
                    onClick={() => handleExport(option.format as any)}
                    className="w-full p-3 bg-gray-50 hover:bg-gray-100 rounded-lg transition-all text-left flex items-center gap-3"
                  >
                    <span className="text-xl">{option.icon}</span>
                    <span className="font-medium text-gray-900">{option.label}</span>
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Canvas */}
        <div className={`${isPreview ? 'lg:col-span-4' : 'lg:col-span-3'}`}>
          <div className="bg-white rounded-2xl p-6 border-2 border-gray-200 shadow-sm min-h-[600px]">
            {widgets.length === 0 ? (
              <div className="h-full flex flex-col items-center justify-center text-center py-20">
                <div className="bg-gradient-to-r from-violet-100 to-purple-100 rounded-full p-6 mb-4">
                  <BarChart3 className="w-16 h-16 text-violet-600" />
                </div>
                <h3 className="text-2xl font-bold text-gray-900 mb-2">Start Building Your Report</h3>
                <p className="text-gray-600 mb-6 max-w-md">
                  Add widgets from the library to create your custom report. Drag and arrange them as you like!
                </p>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {widgets.map((widget) => (
                  <div
                    key={widget.id}
                    onClick={() => !isPreview && setSelectedWidget(widget)}
                    className={`relative rounded-xl transition-all cursor-pointer ${
                      selectedWidget?.id === widget.id && !isPreview
                        ? 'ring-4 ring-violet-500 shadow-xl'
                        : 'hover:shadow-lg'
                    }`}
                    style={{ height: '300px' }}
                  >
                    {!isPreview && (
                      <div className="absolute top-2 right-2 z-10 flex gap-2">
                        <button className="p-1.5 bg-white rounded-lg shadow-md hover:bg-gray-50">
                          <GripVertical className="w-4 h-4 text-gray-600" />
                        </button>
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            handleDeleteWidget(widget.id);
                          }}
                          className="p-1.5 bg-white rounded-lg shadow-md hover:bg-rose-50"
                        >
                          <X className="w-4 h-4 text-rose-600" />
                        </button>
                      </div>
                    )}
                    {renderWidget(widget)}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Schedule Modal */}
      {showScheduleModal && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full p-8">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-2xl font-bold text-gray-900">Schedule Report</h3>
              <button
                onClick={() => setShowScheduleModal(false)}
                className="text-gray-400 hover:text-gray-600"
              >
                <X className="w-6 h-6" />
              </button>
            </div>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Frequency</label>
                <select className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:ring-2 focus:ring-violet-500 focus:border-violet-500">
                  <option>Daily</option>
                  <option>Weekly</option>
                  <option>Monthly</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Time</label>
                <input
                  type="time"
                  defaultValue="09:00"
                  className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:ring-2 focus:ring-violet-500 focus:border-violet-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Recipients</label>
                <input
                  type="email"
                  placeholder="email@example.com"
                  className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:ring-2 focus:ring-violet-500 focus:border-violet-500"
                />
                <p className="text-xs text-gray-500 mt-1">Separate multiple emails with commas</p>
              </div>

              <button className="w-full py-3 bg-gradient-to-r from-violet-600 to-purple-600 text-white rounded-xl hover:from-violet-700 hover:to-purple-700 font-bold transition-all shadow-lg flex items-center justify-center gap-2">
                <Mail className="w-5 h-5" />
                Schedule Report
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default CustomReportBuilder;

