import { NestFactory } from '@nestjs/core';
import { AppModule } from '../app.module';
import { FleetService } from '../modules/fleet/fleet.service';
import { CreateTruckDto } from '../modules/fleet/dto/create-truck.dto';
import { FuelType, TruckType, VehicleStatus } from '../entities/truck.entity';

async function addSampleTrucks() {
  const app = await NestFactory.createApplicationContext(AppModule);

  try {
    console.log('✅ Application context created');

    const fleetService = app.get(FleetService);

    // Sample trucks data
    const sampleTrucks: Partial<CreateTruckDto>[] = [
      {
        plateNumber: 'ABC-123',
        vin: '1HGBH41JXMN109186',
        make: 'Ford',
        model: 'F-150',
        year: 2022,
        color: 'White',
        capacityWeight: 1500,
        capacityVolume: 2.5,
        mileage: 45000,
        fuelType: FuelType.GASOLINE,
        truckType: TruckType.FLATBED,
        insurancePolicy: 'INS-001',
        insuranceExpiry: new Date('2025-12-31'),
        registrationNumber: 'REG-001',
        registrationExpiry: new Date('2025-12-31'),
        roadworthyCertExpiry: new Date('2025-12-31'),
        hasRefrigeration: false,
        hasLiftGate: true,
        hasGps: true,
        hasHazmatPermit: false,
        cargoCapabilities: {
          supportedCargoTypes: ['GENERAL_FREIGHT', 'ELECTRONICS', 'CLOTHING'],
          temperatureRange: { min: -10, max: 30 },
          maxFragileHandling: true,
          maxHazardousHandling: false,
          maxRefrigeratedHandling: false,
          maxLiquidHandling: false,
          maxOversizedHandling: false,
          maxValuableHandling: true,
          maxWeightPerAxle: 1500,
          maxVolumeCapacity: 2.5,
          maxLengthCapacity: 16.5,
          maxWidthCapacity: 2.6,
          maxHeightCapacity: 4.1,
        },
        loadingCapabilities: {
          hasForklift: true,
          hasCrane: false,
          hasLoadingDock: false,
          hasSideLift: false,
          hasTailLift: true,
          hasRollerBed: false,
          hasDropDeck: false,
          hasExtendable: false,
          hasLowbed: false,
          hasStepDeck: false,
          hasPowerOnly: false,
          hasContainerChassis: false,
          maxLoadingTime: 30,
          maxUnloadingTime: 30,
        },
        securityFeatures: {
          hasGps: true,
          hasTracking: true,
          hasTelematics: true,
          hasELD: false,
          hasDashCam: true,
          hasSafetyCameras: true,
          hasCollisionAvoidance: false,
          hasLaneDeparture: false,
          hasAdaptiveCruise: false,
          hasBlindSpot: false,
          hasBackupCamera: true,
          hasTirePressureMonitoring: true,
          hasEngineMonitoring: true,
          hasFuelMonitoring: true,
          hasMaintenanceAlerts: true,
          hasDriverMonitoring: true,
          hasFatigueMonitoring: false,
          hasSpeedMonitoring: true,
          hasIdleMonitoring: true,
          hasRouteOptimization: true,
          hasRealTimeTracking: true,
          hasGeofencing: false,
          hasTemperatureAlerts: false,
          hasHumidityAlerts: false,
          hasShockMonitoring: false,
          hasTiltMonitoring: false,
          hasDoorMonitoring: false,
          hasCargoMonitoring: true,
          hasWeightMonitoring: true,
          hasVolumeMonitoring: true,
          hasPressureMonitoring: false,
          hasFlowMonitoring: false,
          hasLevelMonitoring: false,
          hasQualityMonitoring: false,
          hasContaminationMonitoring: false,
          hasLeakDetection: false,
          hasOverfillProtection: false,
          hasEmergencyShutdown: false,
          hasFireSuppression: false,
          hasExplosionProof: false,
          hasCorrosionResistant: false,
          hasStainlessSteel: false,
          hasAluminum: false,
          hasCarbonSteel: false,
          hasFiberglass: false,
          hasPlastic: false,
          hasComposite: false,
          hasInsulated: false,
        },
      },
      {
        plateNumber: 'XYZ-789',
        vin: '2T1BURHE0JC123456',
        make: 'Chevrolet',
        model: 'Silverado',
        year: 2023,
        color: 'Black',
        capacityWeight: 2000,
        capacityVolume: 3.0,
        mileage: 25000,
        fuelType: FuelType.DIESEL,
        truckType: TruckType.REFRIGERATED,
        insurancePolicy: 'INS-002',
        insuranceExpiry: new Date('2025-12-31'),
        registrationNumber: 'REG-002',
        registrationExpiry: new Date('2025-12-31'),
        roadworthyCertExpiry: new Date('2025-12-31'),
        hasRefrigeration: true,
        hasLiftGate: false,
        hasGps: true,
        hasHazmatPermit: false,
        cargoCapabilities: {
          supportedCargoTypes: [
            'PERISHABLE_GOODS',
            'PHARMACEUTICALS',
            'FROZEN_FOODS',
          ],
          temperatureRange: { min: -20, max: 10 },
          maxFragileHandling: false,
          maxHazardousHandling: false,
          maxRefrigeratedHandling: true,
          maxLiquidHandling: false,
          maxOversizedHandling: false,
          maxValuableHandling: false,
          maxWeightPerAxle: 2000,
          maxVolumeCapacity: 3.0,
          maxLengthCapacity: 18.0,
          maxWidthCapacity: 2.8,
          maxHeightCapacity: 4.5,
        },
        loadingCapabilities: {
          hasForklift: false,
          hasCrane: true,
          hasLoadingDock: true,
          hasSideLift: false,
          hasTailLift: false,
          hasRollerBed: false,
          hasDropDeck: false,
          hasExtendable: false,
          hasLowbed: false,
          hasStepDeck: false,
          hasPowerOnly: false,
          hasContainerChassis: false,
          maxLoadingTime: 45,
          maxUnloadingTime: 45,
        },
        securityFeatures: {
          hasGps: true,
          hasTracking: true,
          hasTelematics: true,
          hasELD: true,
          hasDashCam: true,
          hasSafetyCameras: true,
          hasCollisionAvoidance: true,
          hasLaneDeparture: true,
          hasAdaptiveCruise: true,
          hasBlindSpot: true,
          hasBackupCamera: true,
          hasTirePressureMonitoring: true,
          hasEngineMonitoring: true,
          hasFuelMonitoring: true,
          hasMaintenanceAlerts: true,
          hasDriverMonitoring: true,
          hasFatigueMonitoring: true,
          hasSpeedMonitoring: true,
          hasIdleMonitoring: true,
          hasRouteOptimization: true,
          hasRealTimeTracking: true,
          hasGeofencing: true,
          hasTemperatureAlerts: true,
          hasHumidityAlerts: true,
          hasShockMonitoring: true,
          hasTiltMonitoring: true,
          hasDoorMonitoring: true,
          hasCargoMonitoring: true,
          hasWeightMonitoring: true,
          hasVolumeMonitoring: true,
          hasPressureMonitoring: false,
          hasFlowMonitoring: false,
          hasLevelMonitoring: false,
          hasQualityMonitoring: false,
          hasContaminationMonitoring: false,
          hasLeakDetection: false,
          hasOverfillProtection: false,
          hasEmergencyShutdown: false,
          hasFireSuppression: false,
          hasExplosionProof: false,
          hasCorrosionResistant: false,
          hasStainlessSteel: false,
          hasAluminum: false,
          hasCarbonSteel: false,
          hasFiberglass: false,
          hasPlastic: false,
          hasComposite: false,
          hasInsulated: true,
        },
      },
      {
        plateNumber: 'DEF-456',
        vin: '3VWDX7AJ5DM123789',
        make: 'Toyota',
        model: 'Tacoma',
        year: 2021,
        color: 'Blue',
        capacityWeight: 1200,
        capacityVolume: 2.0,
        mileage: 75000,
        fuelType: FuelType.GASOLINE,
        truckType: TruckType.BOX_TRUCK,
        insurancePolicy: 'INS-003',
        insuranceExpiry: new Date('2025-12-31'),
        registrationNumber: 'REG-003',
        registrationExpiry: new Date('2025-12-31'),
        roadworthyCertExpiry: new Date('2025-12-31'),
        hasRefrigeration: false,
        hasLiftGate: true,
        hasGps: true,
        hasHazmatPermit: false,
        cargoCapabilities: {
          supportedCargoTypes: ['GENERAL_FREIGHT', 'FURNITURE', 'APPLIANCES'],
          temperatureRange: { min: 0, max: 25 },
          maxFragileHandling: false,
          maxHazardousHandling: false,
          maxRefrigeratedHandling: false,
          maxLiquidHandling: false,
          maxOversizedHandling: true,
          maxValuableHandling: false,
          maxWeightPerAxle: 1200,
          maxVolumeCapacity: 2.0,
          maxLengthCapacity: 14.0,
          maxWidthCapacity: 2.4,
          maxHeightCapacity: 3.8,
        },
        loadingCapabilities: {
          hasForklift: true,
          hasCrane: false,
          hasLoadingDock: false,
          hasSideLift: false,
          hasTailLift: false,
          hasRollerBed: false,
          hasDropDeck: false,
          hasExtendable: false,
          hasLowbed: false,
          hasStepDeck: false,
          hasPowerOnly: false,
          hasContainerChassis: false,
          maxLoadingTime: 25,
          maxUnloadingTime: 25,
        },
        securityFeatures: {
          hasGps: true,
          hasTracking: true,
          hasTelematics: true,
          hasELD: false,
          hasDashCam: true,
          hasSafetyCameras: true,
          hasCollisionAvoidance: false,
          hasLaneDeparture: false,
          hasAdaptiveCruise: false,
          hasBlindSpot: false,
          hasBackupCamera: true,
          hasTirePressureMonitoring: true,
          hasEngineMonitoring: true,
          hasFuelMonitoring: true,
          hasMaintenanceAlerts: true,
          hasDriverMonitoring: true,
          hasFatigueMonitoring: false,
          hasSpeedMonitoring: true,
          hasIdleMonitoring: true,
          hasRouteOptimization: true,
          hasRealTimeTracking: true,
          hasGeofencing: false,
          hasTemperatureAlerts: false,
          hasHumidityAlerts: false,
          hasShockMonitoring: false,
          hasTiltMonitoring: false,
          hasDoorMonitoring: false,
          hasCargoMonitoring: true,
          hasWeightMonitoring: true,
          hasVolumeMonitoring: true,
          hasPressureMonitoring: false,
          hasFlowMonitoring: false,
          hasLevelMonitoring: false,
          hasQualityMonitoring: false,
          hasContaminationMonitoring: false,
          hasLeakDetection: false,
          hasOverfillProtection: false,
          hasEmergencyShutdown: false,
          hasFireSuppression: false,
          hasExplosionProof: false,
          hasCorrosionResistant: false,
          hasStainlessSteel: false,
          hasAluminum: false,
          hasCarbonSteel: false,
          hasFiberglass: false,
          hasPlastic: false,
          hasComposite: false,
          hasInsulated: false,
        },
      },
    ];

    console.log('🚛 Adding sample trucks...');

    for (const truckData of sampleTrucks) {
      try {
        // Use a default tenant ID and user ID for testing
        const truck = await fleetService.createTruck(
          truckData as CreateTruckDto,
          'default-user-id', // This should be a real user ID
          'default-tenant-id', // This should be a real tenant ID
        );
        console.log(
          `✅ Created truck: ${truck.plateNumber} - ${truck.make} ${truck.model}`,
        );
      } catch (error) {
        console.error(
          `❌ Failed to create truck ${truckData.plateNumber}:`,
          error.message,
        );
      }
    }

    console.log('✅ Sample trucks added successfully');
  } catch (error) {
    console.error('❌ Error:', error);
  } finally {
    await app.close();
  }
}

addSampleTrucks();
