import {
  Injectable,
  Logger,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { LoadDocument, DocumentType, DocumentStatus } from '../../../entities/load-document.entity';
import { Load } from '../../../entities/load.entity';
import { User, UserRole } from '../../../entities/user.entity';
import { CreateDocumentDto } from '../dto/create-document.dto';

@Injectable()
export class DocumentService {
  private readonly logger = new Logger(DocumentService.name);

  constructor(
    @InjectRepository(LoadDocument)
    private readonly documentRepository: Repository<LoadDocument>,
    @InjectRepository(Load)
    private readonly loadRepository: Repository<Load>,
    @InjectRepository(User)
    private readonly userRepository: Repository<User>,
  ) {}

  /**
   * Create/upload a document
   */
  async createDocument(
    brokerId: string,
    tenantId: string,
    uploadedById: string,
    createDto: CreateDocumentDto,
  ): Promise<LoadDocument> {
    // Verify broker exists
    const broker = await this.userRepository.findOne({
      where: { id: brokerId, role: UserRole.BROKER, tenantId },
    });

    if (!broker) {
      throw new NotFoundException('Broker not found');
    }

    // Verify load exists and is assigned to broker
    const load = await this.loadRepository.findOne({
      where: { id: createDto.loadId, brokerId, tenantId },
    });

    if (!load) {
      throw new NotFoundException('Load not found or not assigned to broker');
    }

    // Create document
    const document = this.documentRepository.create({
      tenantId,
      loadId: createDto.loadId,
      tripId: createDto.tripId,
      brokerId,
      uploadedById,
      documentType: createDto.documentType,
      status: DocumentStatus.DRAFT,
      fileName: createDto.fileName,
      fileUrl: createDto.fileUrl,
      fileType: createDto.fileType,
      fileSize: createDto.fileSize,
      mimeType: createDto.mimeType,
      documentContent: createDto.documentContent,
      documentData: createDto.documentData,
      description: createDto.description,
      expiresAt: createDto.expiresAt ? new Date(createDto.expiresAt) : undefined,
    });

    return this.documentRepository.save(document);
  }

  /**
   * Generate Bill of Lading (BOL)
   */
  async generateBOL(
    brokerId: string,
    tenantId: string,
    loadId: string,
    data?: Record<string, any>,
  ): Promise<LoadDocument> {
    const load = await this.loadRepository.findOne({
      where: { id: loadId, brokerId, tenantId },
      relations: ['cargoOwner', 'broker', 'pickupLocation', 'deliveryLocation'],
    });

    if (!load) {
      throw new NotFoundException('Load not found');
    }

    // Generate BOL content
    const bolContent = this.generateBOLContent(load, data);

    const document = this.documentRepository.create({
      tenantId,
      loadId,
      brokerId,
      uploadedById: brokerId,
      documentType: DocumentType.BILL_OF_LADING,
      status: DocumentStatus.DRAFT,
      fileName: `BOL-${loadId}-${Date.now()}.pdf`,
      fileUrl: '', // Would be generated by document service
      documentContent: bolContent,
      documentData: {
        loadId: load.id,
        cargoOwner: load.cargoOwner?.profile,
        broker: load.broker?.profile,
        pickupLocation: load.pickupLocation,
        deliveryLocation: load.deliveryLocation,
        ...data,
      },
      description: 'Bill of Lading',
    });

    return this.documentRepository.save(document);
  }

  /**
   * Generate Proof of Delivery (POD)
   */
  async generatePOD(
    brokerId: string,
    tenantId: string,
    loadId: string,
    tripId: string,
    data?: Record<string, any>,
  ): Promise<LoadDocument> {
    const load = await this.loadRepository.findOne({
      where: { id: loadId, brokerId, tenantId },
      relations: ['cargoOwner', 'deliveryLocation'],
    });

    if (!load) {
      throw new NotFoundException('Load not found');
    }

    // Generate POD content
    const podContent = this.generatePODContent(load, data);

    const document = this.documentRepository.create({
      tenantId,
      loadId,
      tripId,
      brokerId,
      uploadedById: brokerId,
      documentType: DocumentType.PROOF_OF_DELIVERY,
      status: DocumentStatus.DRAFT,
      fileName: `POD-${loadId}-${Date.now()}.pdf`,
      fileUrl: '', // Would be generated by document service
      documentContent: podContent,
      documentData: {
        loadId: load.id,
        tripId,
        deliveryLocation: load.deliveryLocation,
        deliveredAt: new Date(),
        ...data,
      },
      description: 'Proof of Delivery',
    });

    return this.documentRepository.save(document);
  }

  /**
   * Generate commission invoice
   */
  async generateCommissionInvoice(
    brokerId: string,
    tenantId: string,
    commissionId: string,
    commissionData: {
      amount: number;
      rate: number;
      loadTitle: string;
      loadId: string;
    },
  ): Promise<LoadDocument> {
    const invoiceContent = this.generateInvoiceContent(commissionData);

    const document = this.documentRepository.create({
      tenantId,
      loadId: commissionData.loadId,
      brokerId,
      uploadedById: brokerId,
      documentType: DocumentType.COMMISSION_INVOICE,
      status: DocumentStatus.DRAFT,
      fileName: `Invoice-${commissionId}-${Date.now()}.pdf`,
      fileUrl: '', // Would be generated by document service
      documentContent: invoiceContent,
      documentData: {
        commissionId,
        ...commissionData,
        invoiceDate: new Date(),
      },
      description: 'Commission Invoice',
    });

    return this.documentRepository.save(document);
  }

  /**
   * Get documents for a load
   */
  async getLoadDocuments(
    loadId: string,
    brokerId: string,
    tenantId: string,
    documentType?: DocumentType,
  ): Promise<LoadDocument[]> {
    const where: any = { loadId, brokerId, tenantId };

    if (documentType) {
      where.documentType = documentType;
    }

    return this.documentRepository.find({
      where,
      relations: ['uploadedBy', 'verifiedBy'],
      order: { createdAt: 'DESC' },
    });
  }

  /**
   * Verify document
   */
  async verifyDocument(
    documentId: string,
    brokerId: string,
    tenantId: string,
    verifiedById: string,
    notes?: string,
  ): Promise<LoadDocument> {
    const document = await this.documentRepository.findOne({
      where: { id: documentId, brokerId, tenantId },
    });

    if (!document) {
      throw new NotFoundException('Document not found');
    }

    document.status = DocumentStatus.VERIFIED;
    document.verifiedById = verifiedById;
    document.verifiedAt = new Date();
    document.verificationNotes = notes;

    return this.documentRepository.save(document);
  }

  /**
   * Generate BOL content
   */
  private generateBOLContent(load: Load, data?: Record<string, any>): string {
    return `
BILL OF LADING

Load ID: ${load.id}
Title: ${load.title}

Cargo Owner: ${load.cargoOwner?.profile?.firstName || 'N/A'} ${load.cargoOwner?.profile?.lastName || ''}
Broker: ${load.broker?.profile?.firstName || 'N/A'} ${load.broker?.profile?.lastName || ''}

Pickup Location: ${(load.pickupLocation as any)?.locationData?.address || 'N/A'}
Delivery Location: ${(load.deliveryLocation as any)?.locationData?.address || 'N/A'}

Weight: ${load.weight || 'N/A'} kg
Cargo Type: ${load.cargoType || 'N/A'}

Special Instructions: ${(load as any).specialInstructions || 'None'}

Date: ${new Date().toLocaleDateString()}
    `.trim();
  }

  /**
   * Generate POD content
   */
  private generatePODContent(load: Load, data?: Record<string, any>): string {
    return `
PROOF OF DELIVERY

Load ID: ${load.id}
Title: ${load.title}

Delivered To: ${(load.deliveryLocation as any)?.locationData?.address || 'N/A'}
Delivery Date: ${new Date().toLocaleDateString()}

Cargo Condition: ${data?.condition || 'Good'}
Received By: ${data?.receivedBy || 'N/A'}

Signature: ${data?.signature || 'N/A'}

Notes: ${data?.notes || 'None'}
    `.trim();
  }

  /**
   * Generate invoice content
   */
  private generateInvoiceContent(data: {
    amount: number;
    rate: number;
    loadTitle: string;
  }): string {
    return `
COMMISSION INVOICE

Load: ${data.loadTitle}
Commission Rate: ${data.rate}%
Commission Amount: ${data.amount}

Date: ${new Date().toLocaleDateString()}
    `.trim();
  }
}

