export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  TENANT_ADMIN = 'TENANT_ADMIN',
  MANAGER = 'MANAGER',
  CARGO_OWNER = 'CARGO_OWNER',
  TRUCK_OWNER = 'TRUCK_OWNER',
  DRIVER = 'DRIVER',
  AGENT = 'AGENT',
  LENDER = 'LENDER',
  USER = 'USER',
}
